image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  image: node:latest
  script:
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git HEAD:master
  only:
    - master
